# ゲーム開始までの待機時間
WaitingTime: 30

# 総ゲーム時間
GameTime: 600

# ゲーム開始時間
StartTime: 30

# ゲーム開始可能最少人数 
MinPlayer: 2

# プレイヤー移動速度 デフォルト0.2
WalkSpeed: 0.3

# 範囲に選択される座標を設定
Border:
  higher:
    x: 50
    z: 50
  lower:
    x: -50
    z: -50
  DefaultSize: 500.0