name: LastManStanding
main: tv.twitch.gutitubo.LastManStanding.LastManStanding
version: 1.5.1
author: gutitubo
api-version: 1.14
commands:
    lms:
       description: LastManStanding no Command dayo
       permission: LastManStanding.lms
permissions:
    LastManStanding.*:
       description: LastManStanding no Command dayo
       default: op
    LastManStanding.lms:
       description: LastManStanding no Command dayo
       default: op
    LastManStanding.mj:
       description: LastManStanding no Command dayo
       default: true